JDP211001-15
piotr-grosicki/project-jdp-2110-01 pull request #12
Opened 2021-10-28 16:59 UTC by WojtekRomanowicz

2021-10-30 15:47 UTC, WojtekRomanowicz commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +public class UserMapper {
okej, ale już niech zostanie bo zrobiłem kolejny task w którym trzeba było już ten mapper zrobić więc nie będe tutaj już nic zmieniał ;) Chyba możemy tak to zostawić?

2021-11-02 14:33 UTC, huubsoon commented
w klasie user brakuje listy koszyków i to nad nia powinna być adnotacja oneToMany
wydaje mi się, że jak dasz oneToMany nad listą, a nie jej getterem to wystarczy adnotacja nad klasą getter i setter już nie będzie potrzebny

2021-11-02 14:42 UTC, huubsoon requested changes

2021-11-02 14:42 UTC, huubsoon commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +        @OneToMany(
w klasie user brakuje listy koszyków i to nad nia powinna być adnotacja oneToMany
wydaje mi się, że jak dasz oneToMany nad listą, a nie jej getterem to wystarczy adnotacja nad klasą getter i setter już nie będzie potrzebny

2021-11-08 16:46 UTC, huubsoon approved these changes

2021-11-11 00:37 UTC, mateusz-olszak approved these changes

2021-11-11 00:38 UTC, merged