Jdp211001 21
piotr-grosicki/project-jdp-2110-01 pull request #21
Opened 2021-11-01 18:23 UTC by Matrixx7777

Zmodyfikowałem tą klasę Porduct i ProductDto i inne rzeczy.

2021-11-01 20:18 UTC, huubsoon commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @ManyToOne
Myślę, że warto dodać kolumnę z id grupy

2021-11-01 20:23 UTC, Matrixx7777 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @ManyToOne
Ok

2021-11-01 20:23 UTC, huubsoon commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +@NoArgsConstructor
wydaje mi się, że noargs nie jest potrzebne.

2021-11-01 20:23 UTC, Matrixx7777 commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +@NoArgsConstructor
Dobra to już wywalam

2021-11-02 11:35 UTC, huubsoon commented
program się nie buduje

2021-11-02 11:59 UTC, huubsoon commented
plus wydaje mi się, że wyczyszczenie encji product nie zrobi dobrze aplikacji.

2021-11-02 23:02 UTC, huubsoon requested changes
encja product nie może być pusta. zrób z niej wydmuszkę ze zmiennymi jakich potrzebujesz. 
Prawdopodobnie id oraz group wystarczą.

2021-11-04 07:30 UTC, piotr-grosicki commented
To zadanie jest robione przez inna osobe.

2021-11-04 07:30 UTC, closed without merging