Jdp211001 22
piotr-grosicki/project-jdp-2110-01 pull request #31
Opened 2021-11-04 22:03 UTC by Matrixx7777

2021-11-05 00:16 UTC, mateusz-olszak commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      }
Nie jestem na 100% pewny, ale wydaje mi się, że update encji w ten sposób spowoduje utworzenie nowego rekordu zamiast nadpisania istniejącego już.

2021-11-06 08:47 UTC, huubsoon commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      }
zdecydowanie. wyszukałbym raczej obiekt  po groupId, który chcesz zaktualizować.

2021-11-06 08:49 UTC, huubsoon commented
do create group 
wystarczy param name, bo id generuje sie automatycznie, a lista to new array list, więc do stworzenia potrzebna jest tylko nazwa

w GroupDbService 
@AllArgsConstructor  i @Autowired nie będzie potrzebny 
@RequiredArgs.. jest konstruktorem obiektów niemutowalnych z dodatkiem 'final' 

@mateusz-olszak popraw mnie jeśli się mylę

2021-11-06 13:46 UTC, huubsoon requested changes
wprowadź zmiany zgodnie z komentarzami :)

2021-11-06 22:13 UTC, mateusz-olszak commented
> do create group wystarczy param name, bo id generuje sie automatycznie, a lista to new array list, więc do stworzenia potrzebna jest tylko nazwa
> 
> w GroupDbService @AllArgsConstructor i @Autowired nie będzie potrzebny @RequiredArgs.. jest konstruktorem obiektów niemutowalnych z dodatkiem 'final'
> 
> @mateusz-olszak popraw mnie jeśli się mylę

Hubert dobrze mówi! +1

2021-11-09 22:22 UTC, closed without merging