Group
piotr-grosicki/project-jdp-2110-01 pull request #36
Opened 2021-11-11 14:17 UTC by Matrixx7777

Chciałem dodać adnotacje @Data.

2021-11-11 14:48 UTC, mateusz-olszak approved these changes

2021-11-11 20:00 UTC, huubsoon reviewed
ale w sumie to po co? 
z dokumentacji wywnioskowałem, że jedyna adnotacja, którą zastąpisz to getter, bo nie ma tu hashcodów, toStringi też nie są chyba potrzebne, obiektów typu final brak, więc requiredargsconstructor też nie potrzebny, settera też nie ma.

2021-11-12 21:44 UTC, Matrixx7777 commented
Przekazuję Id i name, untelij mi kazał zamieścić tą adnotacje żebym mógł uzywać setterów w mapperze.

2021-11-13 01:08 UTC, mateusz-olszak commented
Moim zdaniem ta adnotacja nic nie wnosi tutaj, nie jest potrzebna, ale niech ktoś się wypowie, zaakceptuję albo Dawid zamknij tego PR żeby nie wisiał. Poza tym, nazwa brancha wskazuje na zadanie Encją produkt - implementacja tylko ze bez 'x' na końcu co chyba nie powinno tak być.

2021-11-14 17:47 UTC, Matrixx7777 commented
Jeżeli usunę tą adnotacje cały projekt się posypie, ona nic nie szkodzi nikomu chłopaki tylko mi wspomaga implementacje.
Na priv napiszę.

2021-11-14 18:55 UTC, piotr-grosicki commented
Rowniez nie do konca rozumiem sens wrzucania tutaj tak duza adnotacje jak @Data

2021-11-14 20:01 UTC, huubsoon commented
Już wiem. Problem wynika ze źle skonstruowanego mappera Group. Nie używaj metod set, a konstruktora.

2021-11-14 20:04 UTC, huubsoon requested changes
Popraw GroupMapper to Data nie będzie potrzebna

2021-11-14 20:07 UTC, closed without merging